#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyTHPT")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangDiem(BangDiem instance);
    partial void UpdateBangDiem(BangDiem instance);
    partial void DeleteBangDiem(BangDiem instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertGiaoVien(GiaoVien instance);
    partial void UpdateGiaoVien(GiaoVien instance);
    partial void DeleteGiaoVien(GiaoVien instance);
    partial void InsertHocSinh(HocSinh instance);
    partial void UpdateHocSinh(HocSinh instance);
    partial void DeleteHocSinh(HocSinh instance);
    partial void InsertKhoiLop(KhoiLop instance);
    partial void UpdateKhoiLop(KhoiLop instance);
    partial void DeleteKhoiLop(KhoiLop instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertLuong(Luong instance);
    partial void UpdateLuong(Luong instance);
    partial void DeleteLuong(Luong instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    partial void InsertPhanBan(PhanBan instance);
    partial void UpdatePhanBan(PhanBan instance);
    partial void DeletePhanBan(PhanBan instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DAO.Properties.Settings.Default.QuanLyTHPTConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangDiem> BangDiems
		{
			get
			{
				return this.GetTable<BangDiem>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVien> GiaoViens
		{
			get
			{
				return this.GetTable<GiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<HocSinh> HocSinhs
		{
			get
			{
				return this.GetTable<HocSinh>();
			}
		}
		
		public System.Data.Linq.Table<KhoiLop> KhoiLops
		{
			get
			{
				return this.GetTable<KhoiLop>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<Luong> Luongs
		{
			get
			{
				return this.GetTable<Luong>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<PhanBan> PhanBans
		{
			get
			{
				return this.GetTable<PhanBan>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangDiem")]
	public partial class BangDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHS;
		
		private int _maMH;
		
		private string _namHoc;
		
		private System.Nullable<decimal> _tbHocKy1;
		
		private System.Nullable<decimal> _tbHocKy2;
		
		private System.Nullable<decimal> _tbNamHoc;
		
		private EntityRef<HocSinh> _HocSinh;
		
		private EntityRef<MonHoc> _MonHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHSChanging(int value);
    partial void OnmaHSChanged();
    partial void OnmaMHChanging(int value);
    partial void OnmaMHChanged();
    partial void OnnamHocChanging(string value);
    partial void OnnamHocChanged();
    partial void OntbHocKy1Changing(System.Nullable<decimal> value);
    partial void OntbHocKy1Changed();
    partial void OntbHocKy2Changing(System.Nullable<decimal> value);
    partial void OntbHocKy2Changed();
    partial void OntbNamHocChanging(System.Nullable<decimal> value);
    partial void OntbNamHocChanged();
    #endregion
		
		public BangDiem()
		{
			this._HocSinh = default(EntityRef<HocSinh>);
			this._MonHoc = default(EntityRef<MonHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maHS
		{
			get
			{
				return this._maHS;
			}
			set
			{
				if ((this._maHS != value))
				{
					if (this._HocSinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHSChanging(value);
					this.SendPropertyChanging();
					this._maHS = value;
					this.SendPropertyChanged("maHS");
					this.OnmaHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maMH
		{
			get
			{
				return this._maMH;
			}
			set
			{
				if ((this._maMH != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMHChanging(value);
					this.SendPropertyChanging();
					this._maMH = value;
					this.SendPropertyChanged("maMH");
					this.OnmaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namHoc", DbType="VarChar(10)")]
		public string namHoc
		{
			get
			{
				return this._namHoc;
			}
			set
			{
				if ((this._namHoc != value))
				{
					this.OnnamHocChanging(value);
					this.SendPropertyChanging();
					this._namHoc = value;
					this.SendPropertyChanged("namHoc");
					this.OnnamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbHocKy1", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> tbHocKy1
		{
			get
			{
				return this._tbHocKy1;
			}
			set
			{
				if ((this._tbHocKy1 != value))
				{
					this.OntbHocKy1Changing(value);
					this.SendPropertyChanging();
					this._tbHocKy1 = value;
					this.SendPropertyChanged("tbHocKy1");
					this.OntbHocKy1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbHocKy2", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> tbHocKy2
		{
			get
			{
				return this._tbHocKy2;
			}
			set
			{
				if ((this._tbHocKy2 != value))
				{
					this.OntbHocKy2Changing(value);
					this.SendPropertyChanging();
					this._tbHocKy2 = value;
					this.SendPropertyChanged("tbHocKy2");
					this.OntbHocKy2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tbNamHoc", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> tbNamHoc
		{
			get
			{
				return this._tbNamHoc;
			}
			set
			{
				if ((this._tbNamHoc != value))
				{
					this.OntbNamHocChanging(value);
					this.SendPropertyChanging();
					this._tbNamHoc = value;
					this.SendPropertyChanged("tbNamHoc");
					this.OntbNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocSinh_BangDiem", Storage="_HocSinh", ThisKey="maHS", OtherKey="maHS", IsForeignKey=true)]
		public HocSinh HocSinh
		{
			get
			{
				return this._HocSinh.Entity;
			}
			set
			{
				HocSinh previousValue = this._HocSinh.Entity;
				if (((previousValue != value) 
							|| (this._HocSinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocSinh.Entity = null;
						previousValue.BangDiems.Remove(this);
					}
					this._HocSinh.Entity = value;
					if ((value != null))
					{
						value.BangDiems.Add(this);
						this._maHS = value.maHS;
					}
					else
					{
						this._maHS = default(int);
					}
					this.SendPropertyChanged("HocSinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_BangDiem", Storage="_MonHoc", ThisKey="maMH", OtherKey="maMH", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.BangDiems.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.BangDiems.Add(this);
						this._maMH = value.maMH;
					}
					else
					{
						this._maMH = default(int);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCV;
		
		private string _chucVu1;
		
		private System.Nullable<System.DateTime> _ngayNhamChuc;
		
		private System.Nullable<System.DateTime> _ngayKetThuc;
		
		private System.Nullable<int> _nhiemKi;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCVChanging(int value);
    partial void OnmaCVChanged();
    partial void OnchucVu1Changing(string value);
    partial void OnchucVu1Changed();
    partial void OnngayNhamChucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayNhamChucChanged();
    partial void OnngayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKetThucChanged();
    partial void OnnhiemKiChanging(System.Nullable<int> value);
    partial void OnnhiemKiChanged();
    #endregion
		
		public ChucVu()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="chucVu", Storage="_chucVu1", DbType="NVarChar(20)")]
		public string chucVu1
		{
			get
			{
				return this._chucVu1;
			}
			set
			{
				if ((this._chucVu1 != value))
				{
					this.OnchucVu1Changing(value);
					this.SendPropertyChanging();
					this._chucVu1 = value;
					this.SendPropertyChanged("chucVu1");
					this.OnchucVu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayNhamChuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngayNhamChuc
		{
			get
			{
				return this._ngayNhamChuc;
			}
			set
			{
				if ((this._ngayNhamChuc != value))
				{
					this.OnngayNhamChucChanging(value);
					this.SendPropertyChanging();
					this._ngayNhamChuc = value;
					this.SendPropertyChanged("ngayNhamChuc");
					this.OnngayNhamChucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ngayKetThuc
		{
			get
			{
				return this._ngayKetThuc;
			}
			set
			{
				if ((this._ngayKetThuc != value))
				{
					this.OnngayKetThucChanging(value);
					this.SendPropertyChanging();
					this._ngayKetThuc = value;
					this.SendPropertyChanged("ngayKetThuc");
					this.OnngayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhiemKi", DbType="Int")]
		public System.Nullable<int> nhiemKi
		{
			get
			{
				return this._nhiemKi;
			}
			set
			{
				if ((this._nhiemKi != value))
				{
					this.OnnhiemKiChanging(value);
					this.SendPropertyChanging();
					this._nhiemKi = value;
					this.SendPropertyChanged("nhiemKi");
					this.OnnhiemKiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_GiaoVien", Storage="_GiaoViens", ThisKey="maCV", OtherKey="maCV")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVien")]
	public partial class GiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maGV;
		
		private string _hoTenGV;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private string _email;
		
		private string _sdt;
		
		private string _trinhDo;
		
		private string _xepLoai;
		
		private System.Nullable<int> _trangThai;
		
		private System.Nullable<int> _maMH;
		
		private System.Nullable<int> _maCV;
		
		private System.Nullable<int> _maLuong;
		
		private EntitySet<Lop> _Lops;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<Luong> _Luong;
		
		private EntityRef<MonHoc> _MonHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGVChanging(int value);
    partial void OnmaGVChanged();
    partial void OnhoTenGVChanging(string value);
    partial void OnhoTenGVChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OntrinhDoChanging(string value);
    partial void OntrinhDoChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    partial void OnmaMHChanging(System.Nullable<int> value);
    partial void OnmaMHChanged();
    partial void OnmaCVChanging(System.Nullable<int> value);
    partial void OnmaCVChanged();
    partial void OnmaLuongChanging(System.Nullable<int> value);
    partial void OnmaLuongChanged();
    #endregion
		
		public GiaoVien()
		{
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			this._ChucVu = default(EntityRef<ChucVu>);
			this._Luong = default(EntityRef<Luong>);
			this._MonHoc = default(EntityRef<MonHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenGV", DbType="NVarChar(50)")]
		public string hoTenGV
		{
			get
			{
				return this._hoTenGV;
			}
			set
			{
				if ((this._hoTenGV != value))
				{
					this.OnhoTenGVChanging(value);
					this.SendPropertyChanging();
					this._hoTenGV = value;
					this.SendPropertyChanged("hoTenGV");
					this.OnhoTenGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(15)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trinhDo", DbType="NVarChar(50)")]
		public string trinhDo
		{
			get
			{
				return this._trinhDo;
			}
			set
			{
				if ((this._trinhDo != value))
				{
					this.OntrinhDoChanging(value);
					this.SendPropertyChanging();
					this._trinhDo = value;
					this.SendPropertyChanged("trinhDo");
					this.OntrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(15)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMH", DbType="Int")]
		public System.Nullable<int> maMH
		{
			get
			{
				return this._maMH;
			}
			set
			{
				if ((this._maMH != value))
				{
					if (this._MonHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaMHChanging(value);
					this.SendPropertyChanging();
					this._maMH = value;
					this.SendPropertyChanged("maMH");
					this.OnmaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCV", DbType="Int")]
		public System.Nullable<int> maCV
		{
			get
			{
				return this._maCV;
			}
			set
			{
				if ((this._maCV != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCVChanging(value);
					this.SendPropertyChanging();
					this._maCV = value;
					this.SendPropertyChanged("maCV");
					this.OnmaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLuong", DbType="Int")]
		public System.Nullable<int> maLuong
		{
			get
			{
				return this._maLuong;
			}
			set
			{
				if ((this._maLuong != value))
				{
					if (this._Luong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLuongChanging(value);
					this.SendPropertyChanging();
					this._maLuong = value;
					this.SendPropertyChanged("maLuong");
					this.OnmaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_Lop", Storage="_Lops", ThisKey="maGV", OtherKey="maGVCN")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_GiaoVien", Storage="_ChucVu", ThisKey="maCV", OtherKey="maCV", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._maCV = value.maCV;
					}
					else
					{
						this._maCV = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Luong_GiaoVien", Storage="_Luong", ThisKey="maLuong", OtherKey="maLuong", IsForeignKey=true)]
		public Luong Luong
		{
			get
			{
				return this._Luong.Entity;
			}
			set
			{
				Luong previousValue = this._Luong.Entity;
				if (((previousValue != value) 
							|| (this._Luong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Luong.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._Luong.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._maLuong = value.maLuong;
					}
					else
					{
						this._maLuong = default(Nullable<int>);
					}
					this.SendPropertyChanged("Luong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_GiaoVien", Storage="_MonHoc", ThisKey="maMH", OtherKey="maMH", IsForeignKey=true)]
		public MonHoc MonHoc
		{
			get
			{
				return this._MonHoc.Entity;
			}
			set
			{
				MonHoc previousValue = this._MonHoc.Entity;
				if (((previousValue != value) 
							|| (this._MonHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonHoc.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._MonHoc.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._maMH = value.maMH;
					}
					else
					{
						this._maMH = default(Nullable<int>);
					}
					this.SendPropertyChanged("MonHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocSinh")]
	public partial class HocSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHS;
		
		private string _hoTenHS;
		
		private string _gioiTinh;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _dcThuongTru;
		
		private string _dcTamTru;
		
		private string _danToc;
		
		private string _tonGiao;
		
		private string _hoTenCha;
		
		private string _ngheNghiepCha;
		
		private string _hoTenMe;
		
		private string _ngheNghiepMe;
		
		private string _chucVu;
		
		private System.Nullable<int> _trangThai;
		
		private System.Nullable<int> _maLop;
		
		private EntitySet<BangDiem> _BangDiems;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHSChanging(int value);
    partial void OnmaHSChanged();
    partial void OnhoTenHSChanging(string value);
    partial void OnhoTenHSChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OndcThuongTruChanging(string value);
    partial void OndcThuongTruChanged();
    partial void OndcTamTruChanging(string value);
    partial void OndcTamTruChanged();
    partial void OndanTocChanging(string value);
    partial void OndanTocChanged();
    partial void OntonGiaoChanging(string value);
    partial void OntonGiaoChanged();
    partial void OnhoTenChaChanging(string value);
    partial void OnhoTenChaChanged();
    partial void OnngheNghiepChaChanging(string value);
    partial void OnngheNghiepChaChanged();
    partial void OnhoTenMeChanging(string value);
    partial void OnhoTenMeChanged();
    partial void OnngheNghiepMeChanging(string value);
    partial void OnngheNghiepMeChanged();
    partial void OnchucVuChanging(string value);
    partial void OnchucVuChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    partial void OnmaLopChanging(System.Nullable<int> value);
    partial void OnmaLopChanged();
    #endregion
		
		public HocSinh()
		{
			this._BangDiems = new EntitySet<BangDiem>(new Action<BangDiem>(this.attach_BangDiems), new Action<BangDiem>(this.detach_BangDiems));
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHS
		{
			get
			{
				return this._maHS;
			}
			set
			{
				if ((this._maHS != value))
				{
					this.OnmaHSChanging(value);
					this.SendPropertyChanging();
					this._maHS = value;
					this.SendPropertyChanged("maHS");
					this.OnmaHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenHS", DbType="NVarChar(50)")]
		public string hoTenHS
		{
			get
			{
				return this._hoTenHS;
			}
			set
			{
				if ((this._hoTenHS != value))
				{
					this.OnhoTenHSChanging(value);
					this.SendPropertyChanging();
					this._hoTenHS = value;
					this.SendPropertyChanged("hoTenHS");
					this.OnhoTenHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dcThuongTru", DbType="NVarChar(100)")]
		public string dcThuongTru
		{
			get
			{
				return this._dcThuongTru;
			}
			set
			{
				if ((this._dcThuongTru != value))
				{
					this.OndcThuongTruChanging(value);
					this.SendPropertyChanging();
					this._dcThuongTru = value;
					this.SendPropertyChanged("dcThuongTru");
					this.OndcThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dcTamTru", DbType="NVarChar(100)")]
		public string dcTamTru
		{
			get
			{
				return this._dcTamTru;
			}
			set
			{
				if ((this._dcTamTru != value))
				{
					this.OndcTamTruChanging(value);
					this.SendPropertyChanging();
					this._dcTamTru = value;
					this.SendPropertyChanged("dcTamTru");
					this.OndcTamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danToc", DbType="NVarChar(20)")]
		public string danToc
		{
			get
			{
				return this._danToc;
			}
			set
			{
				if ((this._danToc != value))
				{
					this.OndanTocChanging(value);
					this.SendPropertyChanging();
					this._danToc = value;
					this.SendPropertyChanged("danToc");
					this.OndanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tonGiao", DbType="NVarChar(20)")]
		public string tonGiao
		{
			get
			{
				return this._tonGiao;
			}
			set
			{
				if ((this._tonGiao != value))
				{
					this.OntonGiaoChanging(value);
					this.SendPropertyChanging();
					this._tonGiao = value;
					this.SendPropertyChanged("tonGiao");
					this.OntonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenCha", DbType="NVarChar(50)")]
		public string hoTenCha
		{
			get
			{
				return this._hoTenCha;
			}
			set
			{
				if ((this._hoTenCha != value))
				{
					this.OnhoTenChaChanging(value);
					this.SendPropertyChanging();
					this._hoTenCha = value;
					this.SendPropertyChanged("hoTenCha");
					this.OnhoTenChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngheNghiepCha", DbType="NVarChar(20)")]
		public string ngheNghiepCha
		{
			get
			{
				return this._ngheNghiepCha;
			}
			set
			{
				if ((this._ngheNghiepCha != value))
				{
					this.OnngheNghiepChaChanging(value);
					this.SendPropertyChanging();
					this._ngheNghiepCha = value;
					this.SendPropertyChanged("ngheNghiepCha");
					this.OnngheNghiepChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenMe", DbType="NVarChar(50)")]
		public string hoTenMe
		{
			get
			{
				return this._hoTenMe;
			}
			set
			{
				if ((this._hoTenMe != value))
				{
					this.OnhoTenMeChanging(value);
					this.SendPropertyChanging();
					this._hoTenMe = value;
					this.SendPropertyChanged("hoTenMe");
					this.OnhoTenMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngheNghiepMe", DbType="NVarChar(20)")]
		public string ngheNghiepMe
		{
			get
			{
				return this._ngheNghiepMe;
			}
			set
			{
				if ((this._ngheNghiepMe != value))
				{
					this.OnngheNghiepMeChanging(value);
					this.SendPropertyChanging();
					this._ngheNghiepMe = value;
					this.SendPropertyChanged("ngheNghiepMe");
					this.OnngheNghiepMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucVu", DbType="NVarChar(20)")]
		public string chucVu
		{
			get
			{
				return this._chucVu;
			}
			set
			{
				if ((this._chucVu != value))
				{
					this.OnchucVuChanging(value);
					this.SendPropertyChanging();
					this._chucVu = value;
					this.SendPropertyChanged("chucVu");
					this.OnchucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", DbType="Int")]
		public System.Nullable<int> maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocSinh_BangDiem", Storage="_BangDiems", ThisKey="maHS", OtherKey="maHS")]
		public EntitySet<BangDiem> BangDiems
		{
			get
			{
				return this._BangDiems;
			}
			set
			{
				this._BangDiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_HocSinh", Storage="_Lop", ThisKey="maLop", OtherKey="maLop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.HocSinhs.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.HocSinhs.Add(this);
						this._maLop = value.maLop;
					}
					else
					{
						this._maLop = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangDiems(BangDiem entity)
		{
			this.SendPropertyChanging();
			entity.HocSinh = this;
		}
		
		private void detach_BangDiems(BangDiem entity)
		{
			this.SendPropertyChanging();
			entity.HocSinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoiLop")]
	public partial class KhoiLop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKhoi;
		
		private string _tenKhoi;
		
		private System.Nullable<int> _soHS;
		
		private System.Nullable<int> _soLopGioi;
		
		private System.Nullable<int> _soLopKha;
		
		private System.Nullable<int> _soLopTB;
		
		private EntitySet<Lop> _Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoiChanging(int value);
    partial void OnmaKhoiChanged();
    partial void OntenKhoiChanging(string value);
    partial void OntenKhoiChanged();
    partial void OnsoHSChanging(System.Nullable<int> value);
    partial void OnsoHSChanged();
    partial void OnsoLopGioiChanging(System.Nullable<int> value);
    partial void OnsoLopGioiChanged();
    partial void OnsoLopKhaChanging(System.Nullable<int> value);
    partial void OnsoLopKhaChanged();
    partial void OnsoLopTBChanging(System.Nullable<int> value);
    partial void OnsoLopTBChanged();
    #endregion
		
		public KhoiLop()
		{
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKhoi
		{
			get
			{
				return this._maKhoi;
			}
			set
			{
				if ((this._maKhoi != value))
				{
					this.OnmaKhoiChanging(value);
					this.SendPropertyChanging();
					this._maKhoi = value;
					this.SendPropertyChanged("maKhoi");
					this.OnmaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoi", DbType="VarChar(10)")]
		public string tenKhoi
		{
			get
			{
				return this._tenKhoi;
			}
			set
			{
				if ((this._tenKhoi != value))
				{
					this.OntenKhoiChanging(value);
					this.SendPropertyChanging();
					this._tenKhoi = value;
					this.SendPropertyChanged("tenKhoi");
					this.OntenKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soHS", DbType="Int")]
		public System.Nullable<int> soHS
		{
			get
			{
				return this._soHS;
			}
			set
			{
				if ((this._soHS != value))
				{
					this.OnsoHSChanging(value);
					this.SendPropertyChanging();
					this._soHS = value;
					this.SendPropertyChanged("soHS");
					this.OnsoHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLopGioi", DbType="Int")]
		public System.Nullable<int> soLopGioi
		{
			get
			{
				return this._soLopGioi;
			}
			set
			{
				if ((this._soLopGioi != value))
				{
					this.OnsoLopGioiChanging(value);
					this.SendPropertyChanging();
					this._soLopGioi = value;
					this.SendPropertyChanged("soLopGioi");
					this.OnsoLopGioiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLopKha", DbType="Int")]
		public System.Nullable<int> soLopKha
		{
			get
			{
				return this._soLopKha;
			}
			set
			{
				if ((this._soLopKha != value))
				{
					this.OnsoLopKhaChanging(value);
					this.SendPropertyChanging();
					this._soLopKha = value;
					this.SendPropertyChanged("soLopKha");
					this.OnsoLopKhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLopTB", DbType="Int")]
		public System.Nullable<int> soLopTB
		{
			get
			{
				return this._soLopTB;
			}
			set
			{
				if ((this._soLopTB != value))
				{
					this.OnsoLopTBChanging(value);
					this.SendPropertyChanging();
					this._soLopTB = value;
					this.SendPropertyChanged("soLopTB");
					this.OnsoLopTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoiLop_Lop", Storage="_Lops", ThisKey="maKhoi", OtherKey="maKhoi")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.KhoiLop = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.KhoiLop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLop;
		
		private string _tenLop;
		
		private System.Nullable<int> _siSo;
		
		private string _xepLoai;
		
		private System.Nullable<int> _maKhoi;
		
		private System.Nullable<int> _maBan;
		
		private System.Nullable<int> _maGVCN;
		
		private EntitySet<HocSinh> _HocSinhs;
		
		private EntityRef<GiaoVien> _GiaoVien;
		
		private EntityRef<KhoiLop> _KhoiLop;
		
		private EntityRef<PhanBan> _PhanBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLopChanging(int value);
    partial void OnmaLopChanged();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    partial void OnsiSoChanging(System.Nullable<int> value);
    partial void OnsiSoChanged();
    partial void OnxepLoaiChanging(string value);
    partial void OnxepLoaiChanged();
    partial void OnmaKhoiChanging(System.Nullable<int> value);
    partial void OnmaKhoiChanged();
    partial void OnmaBanChanging(System.Nullable<int> value);
    partial void OnmaBanChanged();
    partial void OnmaGVCNChanging(System.Nullable<int> value);
    partial void OnmaGVCNChanged();
    #endregion
		
		public Lop()
		{
			this._HocSinhs = new EntitySet<HocSinh>(new Action<HocSinh>(this.attach_HocSinhs), new Action<HocSinh>(this.detach_HocSinhs));
			this._GiaoVien = default(EntityRef<GiaoVien>);
			this._KhoiLop = default(EntityRef<KhoiLop>);
			this._PhanBan = default(EntityRef<PhanBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLop", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLop
		{
			get
			{
				return this._maLop;
			}
			set
			{
				if ((this._maLop != value))
				{
					this.OnmaLopChanging(value);
					this.SendPropertyChanging();
					this._maLop = value;
					this.SendPropertyChanged("maLop");
					this.OnmaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="VarChar(10)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siSo", DbType="Int")]
		public System.Nullable<int> siSo
		{
			get
			{
				return this._siSo;
			}
			set
			{
				if ((this._siSo != value))
				{
					this.OnsiSoChanging(value);
					this.SendPropertyChanging();
					this._siSo = value;
					this.SendPropertyChanged("siSo");
					this.OnsiSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xepLoai", DbType="NVarChar(15)")]
		public string xepLoai
		{
			get
			{
				return this._xepLoai;
			}
			set
			{
				if ((this._xepLoai != value))
				{
					this.OnxepLoaiChanging(value);
					this.SendPropertyChanging();
					this._xepLoai = value;
					this.SendPropertyChanged("xepLoai");
					this.OnxepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoi", DbType="Int")]
		public System.Nullable<int> maKhoi
		{
			get
			{
				return this._maKhoi;
			}
			set
			{
				if ((this._maKhoi != value))
				{
					if (this._KhoiLop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoiChanging(value);
					this.SendPropertyChanging();
					this._maKhoi = value;
					this.SendPropertyChanged("maKhoi");
					this.OnmaKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", DbType="Int")]
		public System.Nullable<int> maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					if (this._PhanBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGVCN", DbType="Int")]
		public System.Nullable<int> maGVCN
		{
			get
			{
				return this._maGVCN;
			}
			set
			{
				if ((this._maGVCN != value))
				{
					if (this._GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGVCNChanging(value);
					this.SendPropertyChanging();
					this._maGVCN = value;
					this.SendPropertyChanged("maGVCN");
					this.OnmaGVCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_HocSinh", Storage="_HocSinhs", ThisKey="maLop", OtherKey="maLop")]
		public EntitySet<HocSinh> HocSinhs
		{
			get
			{
				return this._HocSinhs;
			}
			set
			{
				this._HocSinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_Lop", Storage="_GiaoVien", ThisKey="maGVCN", OtherKey="maGV", IsForeignKey=true)]
		public GiaoVien GiaoVien
		{
			get
			{
				return this._GiaoVien.Entity;
			}
			set
			{
				GiaoVien previousValue = this._GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVien.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._GiaoVien.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._maGVCN = value.maGV;
					}
					else
					{
						this._maGVCN = default(Nullable<int>);
					}
					this.SendPropertyChanged("GiaoVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoiLop_Lop", Storage="_KhoiLop", ThisKey="maKhoi", OtherKey="maKhoi", IsForeignKey=true)]
		public KhoiLop KhoiLop
		{
			get
			{
				return this._KhoiLop.Entity;
			}
			set
			{
				KhoiLop previousValue = this._KhoiLop.Entity;
				if (((previousValue != value) 
							|| (this._KhoiLop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoiLop.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._KhoiLop.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._maKhoi = value.maKhoi;
					}
					else
					{
						this._maKhoi = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhoiLop");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanBan_Lop", Storage="_PhanBan", ThisKey="maBan", OtherKey="maBan", IsForeignKey=true)]
		public PhanBan PhanBan
		{
			get
			{
				return this._PhanBan.Entity;
			}
			set
			{
				PhanBan previousValue = this._PhanBan.Entity;
				if (((previousValue != value) 
							|| (this._PhanBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanBan.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._PhanBan.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._maBan = value.maBan;
					}
					else
					{
						this._maBan = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HocSinhs(HocSinh entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_HocSinhs(HocSinh entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Luong")]
	public partial class Luong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLuong;
		
		private System.Nullable<decimal> _luongCB;
		
		private System.Nullable<int> _heSoLuong;
		
		private System.Nullable<decimal> _thuong;
		
		private System.Nullable<decimal> _tongLuong;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLuongChanging(int value);
    partial void OnmaLuongChanged();
    partial void OnluongCBChanging(System.Nullable<decimal> value);
    partial void OnluongCBChanged();
    partial void OnheSoLuongChanging(System.Nullable<int> value);
    partial void OnheSoLuongChanged();
    partial void OnthuongChanging(System.Nullable<decimal> value);
    partial void OnthuongChanged();
    partial void OntongLuongChanging(System.Nullable<decimal> value);
    partial void OntongLuongChanged();
    #endregion
		
		public Luong()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLuong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLuong
		{
			get
			{
				return this._maLuong;
			}
			set
			{
				if ((this._maLuong != value))
				{
					this.OnmaLuongChanging(value);
					this.SendPropertyChanging();
					this._maLuong = value;
					this.SendPropertyChanged("maLuong");
					this.OnmaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongCB", DbType="Decimal(9,0)")]
		public System.Nullable<decimal> luongCB
		{
			get
			{
				return this._luongCB;
			}
			set
			{
				if ((this._luongCB != value))
				{
					this.OnluongCBChanging(value);
					this.SendPropertyChanging();
					this._luongCB = value;
					this.SendPropertyChanged("luongCB");
					this.OnluongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heSoLuong", DbType="Int")]
		public System.Nullable<int> heSoLuong
		{
			get
			{
				return this._heSoLuong;
			}
			set
			{
				if ((this._heSoLuong != value))
				{
					this.OnheSoLuongChanging(value);
					this.SendPropertyChanging();
					this._heSoLuong = value;
					this.SendPropertyChanged("heSoLuong");
					this.OnheSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuong", DbType="Decimal(9,0)")]
		public System.Nullable<decimal> thuong
		{
			get
			{
				return this._thuong;
			}
			set
			{
				if ((this._thuong != value))
				{
					this.OnthuongChanging(value);
					this.SendPropertyChanging();
					this._thuong = value;
					this.SendPropertyChanged("thuong");
					this.OnthuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongLuong", DbType="Decimal(9,0)")]
		public System.Nullable<decimal> tongLuong
		{
			get
			{
				return this._tongLuong;
			}
			set
			{
				if ((this._tongLuong != value))
				{
					this.OntongLuongChanging(value);
					this.SendPropertyChanging();
					this._tongLuong = value;
					this.SendPropertyChanged("tongLuong");
					this.OntongLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Luong_GiaoVien", Storage="_GiaoViens", ThisKey="maLuong", OtherKey="maLuong")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.Luong = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.Luong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maMH;
		
		private string _tenMH;
		
		private System.Nullable<int> _soTiet;
		
		private EntitySet<BangDiem> _BangDiems;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaMHChanging(int value);
    partial void OnmaMHChanged();
    partial void OntenMHChanging(string value);
    partial void OntenMHChanged();
    partial void OnsoTietChanging(System.Nullable<int> value);
    partial void OnsoTietChanged();
    #endregion
		
		public MonHoc()
		{
			this._BangDiems = new EntitySet<BangDiem>(new Action<BangDiem>(this.attach_BangDiems), new Action<BangDiem>(this.detach_BangDiems));
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maMH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maMH
		{
			get
			{
				return this._maMH;
			}
			set
			{
				if ((this._maMH != value))
				{
					this.OnmaMHChanging(value);
					this.SendPropertyChanging();
					this._maMH = value;
					this.SendPropertyChanged("maMH");
					this.OnmaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenMH", DbType="NVarChar(25)")]
		public string tenMH
		{
			get
			{
				return this._tenMH;
			}
			set
			{
				if ((this._tenMH != value))
				{
					this.OntenMHChanging(value);
					this.SendPropertyChanging();
					this._tenMH = value;
					this.SendPropertyChanged("tenMH");
					this.OntenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTiet", DbType="Int")]
		public System.Nullable<int> soTiet
		{
			get
			{
				return this._soTiet;
			}
			set
			{
				if ((this._soTiet != value))
				{
					this.OnsoTietChanging(value);
					this.SendPropertyChanging();
					this._soTiet = value;
					this.SendPropertyChanged("soTiet");
					this.OnsoTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_BangDiem", Storage="_BangDiems", ThisKey="maMH", OtherKey="maMH")]
		public EntitySet<BangDiem> BangDiems
		{
			get
			{
				return this._BangDiems;
			}
			set
			{
				this._BangDiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonHoc_GiaoVien", Storage="_GiaoViens", ThisKey="maMH", OtherKey="maMH")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangDiems(BangDiem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_BangDiems(BangDiem entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.MonHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanBan")]
	public partial class PhanBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maBan;
		
		private string _tenBan;
		
		private EntitySet<Lop> _Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBanChanging(int value);
    partial void OnmaBanChanged();
    partial void OntenBanChanging(string value);
    partial void OntenBanChanged();
    #endregion
		
		public PhanBan()
		{
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenBan", DbType="NVarChar(20)")]
		public string tenBan
		{
			get
			{
				return this._tenBan;
			}
			set
			{
				if ((this._tenBan != value))
				{
					this.OntenBanChanging(value);
					this.SendPropertyChanging();
					this._tenBan = value;
					this.SendPropertyChanged("tenBan");
					this.OntenBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanBan_Lop", Storage="_Lops", ThisKey="maBan", OtherKey="maBan")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.PhanBan = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.PhanBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maUser;
		
		private string _tenDangNhap;
		
		private string _matKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaUserChanging(int value);
    partial void OnmaUserChanged();
    partial void OntenDangNhapChanging(string value);
    partial void OntenDangNhapChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maUser", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maUser
		{
			get
			{
				return this._maUser;
			}
			set
			{
				if ((this._maUser != value))
				{
					this.OnmaUserChanging(value);
					this.SendPropertyChanging();
					this._maUser = value;
					this.SendPropertyChanged("maUser");
					this.OnmaUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDangNhap", DbType="VarChar(50)")]
		public string tenDangNhap
		{
			get
			{
				return this._tenDangNhap;
			}
			set
			{
				if ((this._tenDangNhap != value))
				{
					this.OntenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._tenDangNhap = value;
					this.SendPropertyChanged("tenDangNhap");
					this.OntenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(15)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
